import type {
  UserIndicatorType,
  Wma2TimeUnit,
  IndicatorPanel,
  IndicatorFieldKey,
  IndicatorLineWidth,
  IndicatorLineStyle,
} from "../KlinesIndicatorsContext";
import type { FieldOption } from "./useIndicatorsPanelFields";

export interface AddFormState {
  indicatorType: UserIndicatorType;
  period: number;
  periodText: string;
  fieldKey: IndicatorFieldKey;
  color: string;
  colorOpen: boolean;
  chartOption: IndicatorPanel;
  lineWidth: IndicatorLineWidth;
  lineStyle: IndicatorLineStyle;
  macdFastMaType: "SMA" | "EMA" | "WMA";
  macdFastPeriod: number;
  macdFastPeriodText: string;
  macdSlowMaType: "SMA" | "EMA" | "WMA";
  macdSlowPeriod: number;
  macdSlowPeriodText: string;
  macdSignalLine: boolean;
  macdSignalMaType: "SMA" | "EMA" | "WMA";
  macdSignalPeriod: number;
  macdSignalPeriodText: string;
  macdSignalColor: string;
  macdSignalLineWidth: IndicatorLineWidth;
  macdSignalLineStyle: IndicatorLineStyle;
  macdHistogram: boolean;
  macdHistogramColorAbove: string;
  macdHistogramColorBelow: string;
  rsiFixedScale: boolean;
  rsiCenterLine: boolean;
  rsiCenterLineColor: string;
  rsiCenterLineWidth: IndicatorLineWidth;
  rsiCenterLineStyle: IndicatorLineStyle;
  rsiLimits: boolean;
  rsiLimitUpper: number;
  rsiLimitLower: number;
  rsiLimitColor: string;
  rsiLimitLineWidth: IndicatorLineWidth;
  rsiLimitLineStyle: IndicatorLineStyle;
  mfiFixedScale: boolean;
  mfiCenterLine: boolean;
  mfiCenterLineColor: string;
  mfiCenterLineWidth: IndicatorLineWidth;
  mfiCenterLineStyle: IndicatorLineStyle;
  mfiLimits: boolean;
  mfiLimitUpper: number;
  mfiLimitLower: number;
  mfiLimitColor: string;
  mfiLimitLineWidth: IndicatorLineWidth;
  mfiLimitLineStyle: IndicatorLineStyle;
  stochLimits: boolean;
  stochLimitUpper: number;
  stochLimitLower: number;
  stochLimitColor: string;
  stochLimitLineWidth: IndicatorLineWidth;
  stochLimitLineStyle: IndicatorLineStyle;
  stochDLine: boolean;
  stochDMaType: "SMA" | "EMA" | "WMA";
  stochDPeriod: number;
  stochDPeriodText: string;
  stochDColor: string;
  stochDLineWidth: IndicatorLineWidth;
  stochDLineStyle: IndicatorLineStyle;
  williamsRLimits: boolean;
  williamsRLimitUpper: number;
  williamsRLimitLower: number;
  williamsRLimitColor: string;
  williamsRLimitLineWidth: IndicatorLineWidth;
  williamsRLimitLineStyle: IndicatorLineStyle;
  sarStart: number;
  sarStartText: string;
  sarIncrement: number;
  sarIncrementText: string;
  sarMax: number;
  sarMaxText: string;
  sarPointSize: "thin" | "normal";
  bollingerMaType: "SMA" | "EMA" | "WMA";
  bollingerZ: number;
  bollingerZText: string;
  bollingerShowUpper: boolean;
  bollingerShowLower: boolean;
  bollingerShowMiddle: boolean;
  bollingerBandOpacity: number;
  bollingerBandOpacityText: string;
  bollingerLimitsColor: string;
  bollingerLimitsColorOpen: boolean;
  bollingerLimitsLineStyle: IndicatorLineStyle;
  bollingerLimitsLineWidth: IndicatorLineWidth;
  bollingerMiddleColor: string;
  bollingerMiddleLineStyle: IndicatorLineStyle;
  bollingerMiddleLineWidth: IndicatorLineWidth;
  keltnerMaType: "SMA" | "EMA" | "WMA";
  keltnerMultiplier: number;
  keltnerMultiplierText: string;
  keltnerShowUpper: boolean;
  keltnerShowLower: boolean;
  keltnerShowMiddle: boolean;
  keltnerBandOpacity: number;
  keltnerBandOpacityText: string;
  keltnerLimitsColor: string;
  keltnerLimitsColorOpen: boolean;
  keltnerLimitsLineStyle: IndicatorLineStyle;
  keltnerLimitsLineWidth: IndicatorLineWidth;
  keltnerMiddleColor: string;
  keltnerMiddleLineStyle: IndicatorLineStyle;
  keltnerMiddleLineWidth: IndicatorLineWidth;
  obvVolumeSource: "base" | "usdt";
  adVolumeSource: "base" | "usdt";
  volumeInUsdt: boolean;
  volumeColorAbove: string;
  volumeColorBelow: string;
  volumeColorAboveOpen: boolean;
  volumeColorBelowOpen: boolean;
  adxPlusDiColor: string;
  adxPlusDiLineWidth: IndicatorLineWidth;
  adxPlusDiLineStyle: IndicatorLineStyle;
  adxMinusDiColor: string;
  adxMinusDiLineWidth: IndicatorLineWidth;
  adxMinusDiLineStyle: IndicatorLineStyle;
  adxAdxColor: string;
  adxAdxLineWidth: IndicatorLineWidth;
  adxAdxLineStyle: IndicatorLineStyle;
  adxFixedScale: boolean;
  adxLimits: boolean;
  adxLimitUpper: number;
  adxLimitLower: number;
  adxLimitColor: string;
  adxLimitLineWidth: IndicatorLineWidth;
  adxLimitLineStyle: IndicatorLineStyle;
  cciFixedScale: boolean;
  cciLimits: boolean;
  cciLimitUpper: number;
  cciLimitLower: number;
  cciLimitColor: string;
  cciLimitLineWidth: IndicatorLineWidth;
  cciLimitLineStyle: IndicatorLineStyle;
  cciAsHistogram: boolean;
  cciHistogramColorAbove: string;
  cciHistogramColorBelow: string;
  cmfFixedScale: boolean;
  cmfLimits: boolean;
  cmfLimitUpper: number;
  cmfLimitLower: number;
  cmfLimitColor: string;
  cmfLimitLineWidth: IndicatorLineWidth;
  cmfLimitLineStyle: IndicatorLineStyle;
  cmfAsHistogram: boolean;
  cmfHistogramColorAbove: string;
  cmfHistogramColorBelow: string;
  donchianShowUpper: boolean;
  donchianShowLower: boolean;
  donchianShowMiddle: boolean;
  donchianBandOpacity: number;
  donchianBandOpacityText: string;
  donchianLimitsColor: string;
  donchianLimitsLineStyle: IndicatorLineStyle;
  donchianLimitsLineWidth: IndicatorLineWidth;
  donchianMiddleColor: string;
  donchianMiddleLineStyle: IndicatorLineStyle;
  donchianMiddleLineWidth: IndicatorLineWidth;
  ichimokuTenkanPeriod: number;
  ichimokuTenkanPeriodText: string;
  ichimokuKijunPeriod: number;
  ichimokuKijunPeriodText: string;
  ichimokuSpanBPeriod: number;
  ichimokuSpanBPeriodText: string;
  ichimokuDisplacement: number;
  ichimokuDisplacementText: string;
  ichimokuTenkanColor: string;
  ichimokuKijunColor: string;
  ichimokuSpanAColor: string;
  ichimokuSpanBColor: string;
  ichimokuChikouColor: string;
  ichimokuTenkanLineWidth: IndicatorLineWidth;
  ichimokuTenkanLineStyle: IndicatorLineStyle;
  ichimokuKijunLineWidth: IndicatorLineWidth;
  ichimokuKijunLineStyle: IndicatorLineStyle;
  ichimokuSpanALineWidth: IndicatorLineWidth;
  ichimokuSpanALineStyle: IndicatorLineStyle;
  ichimokuSpanBLineWidth: IndicatorLineWidth;
  ichimokuSpanBLineStyle: IndicatorLineStyle;
  ichimokuChikouLineWidth: IndicatorLineWidth;
  ichimokuChikouLineStyle: IndicatorLineStyle;
  ichimokuCloudOpacity: number;
  ichimokuCloudOpacityText: string;
  ichimokuShowTenkan: boolean;
  ichimokuShowKijun: boolean;
  ichimokuShowSpanA: boolean;
  ichimokuShowSpanB: boolean;
  ichimokuShowChikou: boolean;
  wma2TimeUnit: Wma2TimeUnit;
  wma2TimeValue: number;
  wma2TimeValueText: string;
  hmaCustomLongPeriod: number;
  hmaCustomLongPeriodText: string;
  hmaCustomFastPeriod: number;
  hmaCustomFastPeriodText: string;
  hmaCustomSmoothPeriod: number;
  hmaCustomSmoothPeriodText: string;
  hmaCustomLongMaType: "SMA" | "EMA" | "WMA";
  hmaCustomFastMaType: "SMA" | "EMA" | "WMA";
  hmaCustomSmoothMaType: "SMA" | "EMA" | "WMA";
}

export interface EditFormState {
  period: number;
  periodText: string;
  fieldKey: IndicatorFieldKey;
  color: string;
  panel: IndicatorPanel;
  lineWidth: IndicatorLineWidth;
  lineStyle: IndicatorLineStyle;
  rsiFixedScale: boolean;
  rsiCenterLine: boolean;
  rsiCenterLineColor: string;
  rsiCenterLineWidth: IndicatorLineWidth;
  rsiCenterLineStyle: IndicatorLineStyle;
  rsiLimits: boolean;
  rsiLimitUpper: number;
  rsiLimitLower: number;
  rsiLimitColor: string;
  rsiLimitLineWidth: IndicatorLineWidth;
  rsiLimitLineStyle: IndicatorLineStyle;
  mfiFixedScale: boolean;
  mfiCenterLine: boolean;
  mfiCenterLineColor: string;
  mfiCenterLineWidth: IndicatorLineWidth;
  mfiCenterLineStyle: IndicatorLineStyle;
  mfiLimits: boolean;
  mfiLimitUpper: number;
  mfiLimitLower: number;
  mfiLimitColor: string;
  mfiLimitLineWidth: IndicatorLineWidth;
  mfiLimitLineStyle: IndicatorLineStyle;
  macdFastMaType: "SMA" | "EMA" | "WMA";
  macdFastPeriod: number;
  macdFastPeriodText: string;
  macdSlowMaType: "SMA" | "EMA" | "WMA";
  macdSlowPeriod: number;
  macdSlowPeriodText: string;
  macdSignalLine: boolean;
  macdSignalMaType: "SMA" | "EMA" | "WMA";
  macdSignalPeriod: number;
  macdSignalPeriodText: string;
  macdSignalColor: string;
  macdSignalLineWidth: IndicatorLineWidth;
  macdSignalLineStyle: IndicatorLineStyle;
  macdHistogram: boolean;
  macdHistogramColorAbove: string;
  macdHistogramColorBelow: string;
  stochLimits: boolean;
  stochLimitUpper: number;
  stochLimitLower: number;
  stochLimitColor: string;
  stochLimitLineWidth: IndicatorLineWidth;
  stochLimitLineStyle: IndicatorLineStyle;
  stochDLine: boolean;
  stochDMaType: "SMA" | "EMA" | "WMA";
  stochDPeriod: number;
  stochDPeriodText: string;
  stochDColor: string;
  stochDLineWidth: IndicatorLineWidth;
  stochDLineStyle: IndicatorLineStyle;
  williamsRLimits: boolean;
  williamsRLimitUpper: number;
  williamsRLimitLower: number;
  williamsRLimitColor: string;
  williamsRLimitLineWidth: IndicatorLineWidth;
  williamsRLimitLineStyle: IndicatorLineStyle;
  sarStart: number;
  sarStartText: string;
  sarIncrement: number;
  sarIncrementText: string;
  sarMax: number;
  sarMaxText: string;
  sarPointSize: "thin" | "normal";
  bollingerMaType: "SMA" | "EMA" | "WMA";
  bollingerZ: number;
  bollingerZText: string;
  bollingerShowUpper: boolean;
  bollingerShowLower: boolean;
  bollingerShowMiddle: boolean;
  bollingerBandOpacity: number;
  bollingerBandOpacityText: string;
  bollingerLimitsColor: string;
  bollingerLimitsLineStyle: IndicatorLineStyle;
  bollingerLimitsLineWidth: IndicatorLineWidth;
  bollingerMiddleColor: string;
  bollingerMiddleLineStyle: IndicatorLineStyle;
  bollingerMiddleLineWidth: IndicatorLineWidth;
  keltnerMaType: "SMA" | "EMA" | "WMA";
  keltnerMultiplier: number;
  keltnerMultiplierText: string;
  keltnerShowUpper: boolean;
  keltnerShowLower: boolean;
  keltnerShowMiddle: boolean;
  keltnerBandOpacity: number;
  keltnerBandOpacityText: string;
  keltnerLimitsColor: string;
  keltnerLimitsColorOpen: boolean;
  keltnerLimitsLineStyle: IndicatorLineStyle;
  keltnerLimitsLineWidth: IndicatorLineWidth;
  keltnerMiddleColor: string;
  keltnerMiddleLineStyle: IndicatorLineStyle;
  keltnerMiddleLineWidth: IndicatorLineWidth;
  obvVolumeSource: "base" | "usdt";
  adVolumeSource: "base" | "usdt";
  volumeInUsdt: boolean;
  volumeColorAbove: string;
  volumeColorBelow: string;
  adxPlusDiColor: string;
  adxPlusDiLineWidth: IndicatorLineWidth;
  adxPlusDiLineStyle: IndicatorLineStyle;
  adxMinusDiColor: string;
  adxMinusDiLineWidth: IndicatorLineWidth;
  adxMinusDiLineStyle: IndicatorLineStyle;
  adxAdxColor: string;
  adxAdxLineWidth: IndicatorLineWidth;
  adxAdxLineStyle: IndicatorLineStyle;
  adxFixedScale: boolean;
  adxLimits: boolean;
  adxLimitUpper: number;
  adxLimitLower: number;
  adxLimitColor: string;
  adxLimitLineWidth: IndicatorLineWidth;
  adxLimitLineStyle: IndicatorLineStyle;
  cciFixedScale: boolean;
  cciLimits: boolean;
  cciLimitUpper: number;
  cciLimitLower: number;
  cciLimitColor: string;
  cciLimitLineWidth: IndicatorLineWidth;
  cciLimitLineStyle: IndicatorLineStyle;
  cciAsHistogram: boolean;
  cciHistogramColorAbove: string;
  cciHistogramColorBelow: string;
  cmfFixedScale: boolean;
  cmfLimits: boolean;
  cmfLimitUpper: number;
  cmfLimitLower: number;
  cmfLimitColor: string;
  cmfLimitLineWidth: IndicatorLineWidth;
  cmfLimitLineStyle: IndicatorLineStyle;
  cmfAsHistogram: boolean;
  cmfHistogramColorAbove: string;
  cmfHistogramColorBelow: string;
  donchianShowUpper: boolean;
  donchianShowLower: boolean;
  donchianShowMiddle: boolean;
  donchianBandOpacity: number;
  donchianBandOpacityText: string;
  donchianLimitsColor: string;
  donchianLimitsLineStyle: IndicatorLineStyle;
  donchianLimitsLineWidth: IndicatorLineWidth;
  donchianMiddleColor: string;
  donchianMiddleLineStyle: IndicatorLineStyle;
  donchianMiddleLineWidth: IndicatorLineWidth;
  ichimokuTenkanPeriod: number;
  ichimokuTenkanPeriodText: string;
  ichimokuKijunPeriod: number;
  ichimokuKijunPeriodText: string;
  ichimokuSpanBPeriod: number;
  ichimokuSpanBPeriodText: string;
  ichimokuDisplacement: number;
  ichimokuDisplacementText: string;
  ichimokuTenkanColor: string;
  ichimokuKijunColor: string;
  ichimokuSpanAColor: string;
  ichimokuSpanBColor: string;
  ichimokuChikouColor: string;
  ichimokuTenkanLineWidth: IndicatorLineWidth;
  ichimokuTenkanLineStyle: IndicatorLineStyle;
  ichimokuKijunLineWidth: IndicatorLineWidth;
  ichimokuKijunLineStyle: IndicatorLineStyle;
  ichimokuSpanALineWidth: IndicatorLineWidth;
  ichimokuSpanALineStyle: IndicatorLineStyle;
  ichimokuSpanBLineWidth: IndicatorLineWidth;
  ichimokuSpanBLineStyle: IndicatorLineStyle;
  ichimokuChikouLineWidth: IndicatorLineWidth;
  ichimokuChikouLineStyle: IndicatorLineStyle;
  ichimokuCloudOpacity: number;
  ichimokuCloudOpacityText: string;
  ichimokuShowTenkan: boolean;
  ichimokuShowKijun: boolean;
  ichimokuShowSpanA: boolean;
  ichimokuShowSpanB: boolean;
  ichimokuShowChikou: boolean;
  wma2TimeUnit: Wma2TimeUnit;
  wma2TimeValue: number;
  wma2TimeValueText: string;
  hmaCustomLongPeriod: number;
  hmaCustomLongPeriodText: string;
  hmaCustomFastPeriod: number;
  hmaCustomFastPeriodText: string;
  hmaCustomSmoothPeriod: number;
  hmaCustomSmoothPeriodText: string;
  hmaCustomLongMaType: "SMA" | "EMA" | "WMA";
  hmaCustomFastMaType: "SMA" | "EMA" | "WMA";
  hmaCustomSmoothMaType: "SMA" | "EMA" | "WMA";
  showLastValueOnYAxis: boolean;
  intervals: number[];
}

export interface IndicatorsPanelContextValue {
  t: Record<string, string>;
  userIndicators: import("../KlinesIndicatorsContext").UserIndicatorConfig[];
  fieldOptions: FieldOption[];
  firstEnabledFieldValue: IndicatorFieldKey;
  fieldOptionsVisibleForAdd: FieldOption[];
  firstEnabledFieldValueForAdd: IndicatorFieldKey;
  panelsWithSecondary: { panel2: boolean; panel3: boolean; panel4: boolean; panel5: boolean };
  panelsFreeForSecondary: { panel2: boolean; panel3: boolean; panel4: boolean; panel5: boolean };
  panelsFreeForSecondaryEdit: { panel2: boolean; panel3: boolean; panel4: boolean; panel5: boolean };
  indicatorCountByPanel: { main: number; panel2: number; panel3: number; panel4: number; panel5: number };
  /** Modo free: painéis 3, 4 e 5 não podem ser selecionados. */
  isFreeUser?: boolean;
  MAIN_MAX_INDICATORS: number;
  SECONDARY_MAX_INDICATORS: number;
  isMovingAverageType: (type: string) => boolean;
  INDICATOR_COLOR_PALETTE: readonly string[];
  INTERVAL_OPTIONS: { value: number; label: string }[];
  addButtonDisabled: boolean;
  /** true quando o layout ativo é modelo default e já há DEFAULT_MODEL_MAX_INDICATORS indicadores. */
  defaultModelMaxIndicatorsReached?: boolean;
  /** true quando o layout ativo é default (slot 0): só alguns tipos de indicador podem ser usados. */
  isDefaultLayout?: boolean;
  handleAdd: () => void;
  editingId: string | null;
  editForm: EditFormState | null;
  setEditForm: React.Dispatch<React.SetStateAction<EditFormState | null>>;
  startEdit: (ind: import("../KlinesIndicatorsContext").UserIndicatorConfig) => void;
  saveEdit: () => void;
  cancelEdit: () => void;
  expandedId: string | null;
  setExpandedId: (id: string | null) => void;
  toggleInterval: (id: string, groupMinutes: number) => void;
  setAllIntervals: (id: string) => void;
  isIntervalChecked: (ind: import("../KlinesIndicatorsContext").UserIndicatorConfig, value: number) => boolean;
  removeIndicator: (id: string) => void;
  updateIndicator: (id: string, updates: Partial<import("../KlinesIndicatorsContext").UserIndicatorEditable>) => void;
  getIndicatorLabel: (ind: import("../KlinesIndicatorsContext").UserIndicatorConfig, t: unknown, list: import("../KlinesIndicatorsContext").UserIndicatorConfig[]) => string;
}
