import type {
  UserIndicatorType,
  IndicatorPanel,
  IndicatorFieldKey,
  IndicatorLineWidth,
  IndicatorLineStyle,
} from "../KlinesIndicatorsContext";
import type { FieldOption } from "./useIndicatorsPanelFields";

export interface AddFormState {
  indicatorType: UserIndicatorType;
  period: number;
  periodText: string;
  fieldKey: IndicatorFieldKey;
  color: string;
  colorOpen: boolean;
  chartOption: IndicatorPanel;
  lineWidth: IndicatorLineWidth;
  lineStyle: IndicatorLineStyle;
  macdFastMaType: "SMA" | "EMA" | "WMA";
  macdFastPeriod: number;
  macdFastPeriodText: string;
  macdSlowMaType: "SMA" | "EMA" | "WMA";
  macdSlowPeriod: number;
  macdSlowPeriodText: string;
  macdSignalLine: boolean;
  macdSignalMaType: "SMA" | "EMA" | "WMA";
  macdSignalPeriod: number;
  macdSignalPeriodText: string;
  macdSignalColor: string;
  macdSignalLineWidth: IndicatorLineWidth;
  macdSignalLineStyle: IndicatorLineStyle;
  macdHistogram: boolean;
  macdHistogramColorAbove: string;
  macdHistogramColorBelow: string;
  rsiFixedScale: boolean;
  rsiCenterLine: boolean;
  rsiCenterLineColor: string;
  rsiCenterLineWidth: IndicatorLineWidth;
  rsiCenterLineStyle: IndicatorLineStyle;
  rsiLimits: boolean;
  rsiLimitUpper: number;
  rsiLimitLower: number;
  rsiLimitColor: string;
  rsiLimitLineWidth: IndicatorLineWidth;
  rsiLimitLineStyle: IndicatorLineStyle;
  stochLimits: boolean;
  stochLimitUpper: number;
  stochLimitLower: number;
  stochLimitColor: string;
  stochLimitLineWidth: IndicatorLineWidth;
  stochLimitLineStyle: IndicatorLineStyle;
  stochDLine: boolean;
  stochDMaType: "SMA" | "EMA" | "WMA";
  stochDPeriod: number;
  stochDPeriodText: string;
  stochDColor: string;
  stochDLineWidth: IndicatorLineWidth;
  stochDLineStyle: IndicatorLineStyle;
  williamsRLimits: boolean;
  williamsRLimitUpper: number;
  williamsRLimitLower: number;
  williamsRLimitColor: string;
  williamsRLimitLineWidth: IndicatorLineWidth;
  williamsRLimitLineStyle: IndicatorLineStyle;
  sarStart: number;
  sarStartText: string;
  sarIncrement: number;
  sarIncrementText: string;
  sarMax: number;
  sarMaxText: string;
  sarPointSize: "thin" | "normal";
  bollingerMaType: "SMA" | "EMA" | "WMA";
  bollingerZ: number;
  bollingerZText: string;
  bollingerShowUpper: boolean;
  bollingerShowLower: boolean;
  bollingerShowMiddle: boolean;
  bollingerBandOpacity: number;
  bollingerBandOpacityText: string;
  bollingerLimitsColor: string;
  bollingerLimitsColorOpen: boolean;
  bollingerLimitsLineStyle: IndicatorLineStyle;
  bollingerLimitsLineWidth: IndicatorLineWidth;
  bollingerMiddleColor: string;
  bollingerMiddleLineStyle: IndicatorLineStyle;
  bollingerMiddleLineWidth: IndicatorLineWidth;
  volumeInUsdt: boolean;
  volumeColorAbove: string;
  volumeColorBelow: string;
  volumeColorAboveOpen: boolean;
  volumeColorBelowOpen: boolean;
}

export interface EditFormState {
  period: number;
  periodText: string;
  fieldKey: IndicatorFieldKey;
  color: string;
  panel: IndicatorPanel;
  lineWidth: IndicatorLineWidth;
  lineStyle: IndicatorLineStyle;
  rsiFixedScale: boolean;
  rsiCenterLine: boolean;
  rsiCenterLineColor: string;
  rsiCenterLineWidth: IndicatorLineWidth;
  rsiCenterLineStyle: IndicatorLineStyle;
  rsiLimits: boolean;
  rsiLimitUpper: number;
  rsiLimitLower: number;
  rsiLimitColor: string;
  rsiLimitLineWidth: IndicatorLineWidth;
  rsiLimitLineStyle: IndicatorLineStyle;
  macdFastMaType: "SMA" | "EMA" | "WMA";
  macdFastPeriod: number;
  macdFastPeriodText: string;
  macdSlowMaType: "SMA" | "EMA" | "WMA";
  macdSlowPeriod: number;
  macdSlowPeriodText: string;
  macdSignalLine: boolean;
  macdSignalMaType: "SMA" | "EMA" | "WMA";
  macdSignalPeriod: number;
  macdSignalPeriodText: string;
  macdSignalColor: string;
  macdSignalLineWidth: IndicatorLineWidth;
  macdSignalLineStyle: IndicatorLineStyle;
  macdHistogram: boolean;
  macdHistogramColorAbove: string;
  macdHistogramColorBelow: string;
  stochLimits: boolean;
  stochLimitUpper: number;
  stochLimitLower: number;
  stochLimitColor: string;
  stochLimitLineWidth: IndicatorLineWidth;
  stochLimitLineStyle: IndicatorLineStyle;
  stochDLine: boolean;
  stochDMaType: "SMA" | "EMA" | "WMA";
  stochDPeriod: number;
  stochDPeriodText: string;
  stochDColor: string;
  stochDLineWidth: IndicatorLineWidth;
  stochDLineStyle: IndicatorLineStyle;
  williamsRLimits: boolean;
  williamsRLimitUpper: number;
  williamsRLimitLower: number;
  williamsRLimitColor: string;
  williamsRLimitLineWidth: IndicatorLineWidth;
  williamsRLimitLineStyle: IndicatorLineStyle;
  sarStart: number;
  sarStartText: string;
  sarIncrement: number;
  sarIncrementText: string;
  sarMax: number;
  sarMaxText: string;
  sarPointSize: "thin" | "normal";
  bollingerMaType: "SMA" | "EMA" | "WMA";
  bollingerZ: number;
  bollingerZText: string;
  bollingerShowUpper: boolean;
  bollingerShowLower: boolean;
  bollingerShowMiddle: boolean;
  bollingerBandOpacity: number;
  bollingerBandOpacityText: string;
  bollingerLimitsColor: string;
  bollingerLimitsLineStyle: IndicatorLineStyle;
  bollingerLimitsLineWidth: IndicatorLineWidth;
  bollingerMiddleColor: string;
  bollingerMiddleLineStyle: IndicatorLineStyle;
  bollingerMiddleLineWidth: IndicatorLineWidth;
  volumeInUsdt: boolean;
  volumeColorAbove: string;
  volumeColorBelow: string;
}

export interface IndicatorsPanelContextValue {
  t: Record<string, string>;
  userIndicators: import("../KlinesIndicatorsContext").UserIndicatorConfig[];
  fieldOptions: FieldOption[];
  firstEnabledFieldValue: IndicatorFieldKey;
  fieldOptionsVisibleForAdd: FieldOption[];
  firstEnabledFieldValueForAdd: IndicatorFieldKey;
  panelsWithSecondary: { panel2: boolean; panel3: boolean; panel4: boolean; panel5: boolean };
  panelsFreeForSecondary: { panel2: boolean; panel3: boolean; panel4: boolean; panel5: boolean };
  panelsFreeForSecondaryEdit: { panel2: boolean; panel3: boolean; panel4: boolean; panel5: boolean };
  indicatorCountByPanel: { main: number; panel2: number; panel3: number; panel4: number; panel5: number };
  MAIN_MAX_INDICATORS: number;
  SECONDARY_MAX_INDICATORS: number;
  isMovingAverageType: (type: string) => boolean;
  INDICATOR_COLOR_PALETTE: readonly string[];
  INTERVAL_OPTIONS: { value: number; label: string }[];
  addButtonDisabled: boolean;
  handleAdd: () => void;
  editingId: string | null;
  editForm: EditFormState | null;
  setEditForm: React.Dispatch<React.SetStateAction<EditFormState | null>>;
  startEdit: (ind: import("../KlinesIndicatorsContext").UserIndicatorConfig) => void;
  saveEdit: () => void;
  cancelEdit: () => void;
  expandedId: string | null;
  setExpandedId: (id: string | null) => void;
  toggleInterval: (id: string, groupMinutes: number) => void;
  setAllIntervals: (id: string) => void;
  isIntervalChecked: (ind: import("../KlinesIndicatorsContext").UserIndicatorConfig, value: number) => boolean;
  removeIndicator: (id: string) => void;
  updateIndicator: (id: string, updates: Partial<import("../KlinesIndicatorsContext").UserIndicatorEditable>) => void;
  getIndicatorLabel: (ind: import("../KlinesIndicatorsContext").UserIndicatorConfig, t: unknown, list: import("../KlinesIndicatorsContext").UserIndicatorConfig[]) => string;
}
