
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */
// biome-ignore-all lint: generated file

Object.defineProperty(exports, "__esModule", { value: true });

const {
  Decimal,
  objectEnumValues,
  makeStrictEnum,
  Public,
  getRuntime,
  skip
} = require('./runtime/index-browser.js')


const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 6.19.2
 * Query Engine version: c2990dca591cba766e3b7ef5d9e8a84796e47ab7
 */
Prisma.prismaVersion = {
  client: "6.19.2",
  engine: "c2990dca591cba766e3b7ef5d9e8a84796e47ab7"
}

Prisma.PrismaClientKnownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientKnownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)};
Prisma.PrismaClientUnknownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientUnknownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientRustPanicError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientRustPanicError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientInitializationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientInitializationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientValidationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientValidationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`sqltag is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.empty = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`empty is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.join = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`join is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.raw = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`raw is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.validator = Public.validator

/**
* Extensions
*/
Prisma.getExtensionContext = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.getExtensionContext is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.defineExtension = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.defineExtension is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = objectEnumValues.instances.DbNull
Prisma.JsonNull = objectEnumValues.instances.JsonNull
Prisma.AnyNull = objectEnumValues.instances.AnyNull

Prisma.NullTypes = {
  DbNull: objectEnumValues.classes.DbNull,
  JsonNull: objectEnumValues.classes.JsonNull,
  AnyNull: objectEnumValues.classes.AnyNull
}



/**
 * Enums
 */

exports.Prisma.TransactionIsolationLevel = makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
});

exports.Prisma.UserScalarFieldEnum = {
  id: 'id',
  emailEnc: 'emailEnc',
  emailIv: 'emailIv',
  emailTag: 'emailTag',
  emailSearchHash: 'emailSearchHash',
  emailVerifiedAt: 'emailVerifiedAt',
  name: 'name',
  passwordHash: 'passwordHash',
  specialCodeHash: 'specialCodeHash',
  specialExpiresAt: 'specialExpiresAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  role: 'role',
  tier: 'tier',
  nickname: 'nickname',
  nicknameChanges: 'nicknameChanges',
  avatarId: 'avatarId',
  avatarBorder: 'avatarBorder',
  avatarSkinTone: 'avatarSkinTone',
  avatarColorTone: 'avatarColorTone',
  sevenPoints: 'sevenPoints',
  ganhoSimulado: 'ganhoSimulado',
  userLevel: 'userLevel',
  position: 'position',
  tmp: 'tmp',
  isDeleted: 'isDeleted',
  dataExclusao: 'dataExclusao',
  dataExpiracao: 'dataExpiracao',
  pushToken: 'pushToken',
  pushTokenUpdated: 'pushTokenUpdated',
  notifyMegaSena: 'notifyMegaSena',
  notifyLotofacil: 'notifyLotofacil',
  notifyQuina: 'notifyQuina',
  hideStatusBar: 'hideStatusBar',
  progress: 'progress',
  language: 'language',
  timezoneOffset: 'timezoneOffset',
  activeTabId: 'activeTabId',
  activeTabUpdatedAt: 'activeTabUpdatedAt',
  previousTabId: 'previousTabId',
  previousTabUpdatedAt: 'previousTabUpdatedAt'
};

exports.Prisma.UserBinanceConnectionScalarFieldEnum = {
  userId: 'userId',
  payloadEnc: 'payloadEnc',
  payloadIv: 'payloadIv',
  payloadTag: 'payloadTag',
  apiKeyLast4: 'apiKeyLast4',
  lastVerifiedAt: 'lastVerifiedAt',
  defaultQuoteUsdtPerOrder: 'defaultQuoteUsdtPerOrder',
  feeEstimateTakerFallback: 'feeEstimateTakerFallback',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.UserBinanceSpotOrderScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  symbol: 'symbol',
  binanceOrderId: 'binanceOrderId',
  side: 'side',
  orderType: 'orderType',
  status: 'status',
  price: 'price',
  origQty: 'origQty',
  executedQty: 'executedQty',
  rawJson: 'rawJson',
  canceledAt: 'canceledAt',
  createdAt: 'createdAt'
};

exports.Prisma.AffiliateAccountScalarFieldEnum = {
  id: 'id',
  emailEnc: 'emailEnc',
  emailIv: 'emailIv',
  emailTag: 'emailTag',
  emailSearchHash: 'emailSearchHash',
  passwordHash: 'passwordHash',
  ativo: 'ativo',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  lastLoginAt: 'lastLoginAt',
  lastPlanPaymentPayoutSyncAt: 'lastPlanPaymentPayoutSyncAt'
};

exports.Prisma.AffiliateCouponScalarFieldEnum = {
  id: 'id',
  affiliateAccountId: 'affiliateAccountId',
  code: 'code',
  createdAt: 'createdAt',
  ativo: 'ativo',
  expiresAt: 'expiresAt'
};

exports.Prisma.ChartLayoutScalarFieldEnum = {
  userId: 'userId',
  slot: 'slot',
  layout: 'layout',
  indicators: 'indicators',
  strategies: 'strategies',
  regressions: 'regressions',
  others: 'others',
  robots: 'robots',
  name: 'name',
  updatedAt: 'updatedAt'
};

exports.Prisma.ChartModelScalarFieldEnum = {
  userId: 'userId',
  slot: 'slot',
  layout: 'layout',
  indicators: 'indicators',
  strategies: 'strategies',
  regressions: 'regressions',
  others: 'others',
  name: 'name',
  updatedAt: 'updatedAt'
};

exports.Prisma.UserNotificationScalarFieldEnum = {
  idNotification: 'idNotification',
  senderType: 'senderType',
  sender: 'sender',
  userId: 'userId',
  notification: 'notification',
  keySystem: 'keySystem',
  ativo: 'ativo',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  expiredDate: 'expiredDate'
};

exports.Prisma.AccessRequestScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  message: 'message',
  status: 'status',
  createdAt: 'createdAt'
};

exports.Prisma.EmailVerificationTokenScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  tokenHash: 'tokenHash',
  expiresAt: 'expiresAt',
  createdAt: 'createdAt'
};

exports.Prisma.PasswordResetTokenScalarFieldEnum = {
  tokenHash: 'tokenHash',
  userId: 'userId',
  expiresAt: 'expiresAt',
  createdAt: 'createdAt'
};

exports.Prisma.UserCoinWalletScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  balance: 'balance',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.CoinLedgerEntryScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  walletId: 'walletId',
  type: 'type',
  source: 'source',
  amount: 'amount',
  refId: 'refId',
  meta: 'meta',
  createdAt: 'createdAt'
};

exports.Prisma.WalletCreditScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  entryId: 'entryId',
  amount: 'amount',
  consumed: 'consumed',
  expiresAt: 'expiresAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.StripeEventScalarFieldEnum = {
  id: 'id',
  type: 'type',
  payload: 'payload',
  receivedAt: 'receivedAt',
  processedAt: 'processedAt'
};

exports.Prisma.StripeCheckoutSessionScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  status: 'status',
  amountTotalCents: 'amountTotalCents',
  currency: 'currency',
  coinsToCredit: 'coinsToCredit',
  pricingLabel: 'pricingLabel',
  completedAt: 'completedAt',
  createdAt: 'createdAt'
};

exports.Prisma.StripePlanPaymentScalarFieldEnum = {
  id: 'id',
  provider: 'provider',
  userId: 'userId',
  invoiceId: 'invoiceId',
  checkoutSessionId: 'checkoutSessionId',
  pagarmeOrderId: 'pagarmeOrderId',
  subscriptionId: 'subscriptionId',
  paymentIntentId: 'paymentIntentId',
  chargeId: 'chargeId',
  cupomId: 'cupomId',
  idAfiliado: 'idAfiliado',
  planKey: 'planKey',
  amountTotalCents: 'amountTotalCents',
  currency: 'currency',
  amountAffiliateCents: 'amountAffiliateCents',
  currencyAffiliate: 'currencyAffiliate',
  commissionAffiliateCents: 'commissionAffiliateCents',
  coinsCredited: 'coinsCredited',
  pricingLabel: 'pricingLabel',
  paidAt: 'paidAt',
  createdAt: 'createdAt',
  situacao: 'situacao',
  stripePayoutId: 'stripePayoutId',
  pagarmePayoutId: 'pagarmePayoutId',
  payoutStatus: 'payoutStatus',
  payoutArrivalDate: 'payoutArrivalDate',
  payoutUpdatedAt: 'payoutUpdatedAt'
};

exports.Prisma.AffiliatePlanPaymentMonthAggScalarFieldEnum = {
  id: 'id',
  idAfiliado: 'idAfiliado',
  monthStart: 'monthStart',
  totalAmountCents: 'totalAmountCents',
  totalReembolsadoCents: 'totalReembolsadoCents',
  totalAprovadoCents: 'totalAprovadoCents',
  totalAffiliateCents: 'totalAffiliateCents',
  totalReembolsadoAffiliateCents: 'totalReembolsadoAffiliateCents',
  totalAprovadoAffiliateCents: 'totalAprovadoAffiliateCents',
  totalCommissionAffiliateCents: 'totalCommissionAffiliateCents',
  totalReembolsadoCommissionAffiliateCents: 'totalReembolsadoCommissionAffiliateCents',
  totalAprovadoCommissionAffiliateCents: 'totalAprovadoCommissionAffiliateCents',
  totalExpiradoCommissionAffiliateCents: 'totalExpiradoCommissionAffiliateCents',
  currencyAffiliate: 'currencyAffiliate',
  expiresAt: 'expiresAt',
  status: 'status',
  updatedAt: 'updatedAt'
};

exports.Prisma.AffiliateMonthAggInvoiceScalarFieldEnum = {
  id: 'id',
  monthAggId: 'monthAggId',
  pdfBytes: 'pdfBytes',
  fileName: 'fileName',
  contentType: 'contentType',
  sizeBytes: 'sizeBytes',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.PagarMeOrderScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  status: 'status',
  amountTotalCents: 'amountTotalCents',
  currency: 'currency',
  coinsToCredit: 'coinsToCredit',
  pricingLabel: 'pricingLabel',
  qrCode: 'qrCode',
  qrCodeUrl: 'qrCodeUrl',
  pixCopyPaste: 'pixCopyPaste',
  expiresAt: 'expiresAt',
  completedAt: 'completedAt',
  createdAt: 'createdAt'
};

exports.Prisma.BinanceKlineScalarFieldEnum = {
  corretora: 'corretora',
  symbol: 'symbol',
  interval: 'interval',
  openTime: 'openTime',
  open: 'open',
  high: 'high',
  low: 'low',
  close: 'close',
  volume: 'volume',
  closeTime: 'closeTime',
  quoteAssetVolume: 'quoteAssetVolume',
  numberOfTrades: 'numberOfTrades',
  takerBuyBaseAssetVolume: 'takerBuyBaseAssetVolume',
  takerBuyQuoteAssetVolume: 'takerBuyQuoteAssetVolume'
};

exports.Prisma.BinanceKlineFastScalarFieldEnum = {
  corretora: 'corretora',
  symbol: 'symbol',
  interval: 'interval',
  openTime: 'openTime',
  open: 'open',
  high: 'high',
  low: 'low',
  close: 'close',
  volume: 'volume',
  closeTime: 'closeTime',
  quoteAssetVolume: 'quoteAssetVolume',
  numberOfTrades: 'numberOfTrades',
  takerBuyBaseAssetVolume: 'takerBuyBaseAssetVolume',
  takerBuyQuoteAssetVolume: 'takerBuyQuoteAssetVolume'
};

exports.Prisma.BinanceRenkoFastScalarFieldEnum = {
  corretora: 'corretora',
  symbol: 'symbol',
  interval: 'interval',
  openTime: 'openTime',
  open: 'open',
  high: 'high',
  low: 'low',
  close: 'close',
  volume: 'volume',
  closeTime: 'closeTime',
  quoteAssetVolume: 'quoteAssetVolume',
  numberOfTrades: 'numberOfTrades',
  takerBuyBaseAssetVolume: 'takerBuyBaseAssetVolume',
  takerBuyQuoteAssetVolume: 'takerBuyQuoteAssetVolume',
  k2Incl5ticks: 'k2Incl5ticks',
  k2Incl15ticks: 'k2Incl15ticks',
  k2Incl25ticks: 'k2Incl25ticks',
  k2Incl50ticks: 'k2Incl50ticks',
  k2Incl100ticks: 'k2Incl100ticks',
  k2Incl150ticks: 'k2Incl150ticks',
  k2Incl200ticks: 'k2Incl200ticks'
};

exports.Prisma.BinanceRangeFastScalarFieldEnum = {
  corretora: 'corretora',
  symbol: 'symbol',
  interval: 'interval',
  openTime: 'openTime',
  open: 'open',
  high: 'high',
  low: 'low',
  close: 'close',
  volume: 'volume',
  closeTime: 'closeTime',
  quoteAssetVolume: 'quoteAssetVolume',
  numberOfTrades: 'numberOfTrades',
  takerBuyBaseAssetVolume: 'takerBuyBaseAssetVolume',
  takerBuyQuoteAssetVolume: 'takerBuyQuoteAssetVolume',
  k2Incl5ticks: 'k2Incl5ticks',
  k2Incl15ticks: 'k2Incl15ticks',
  k2Incl25ticks: 'k2Incl25ticks',
  k2Incl50ticks: 'k2Incl50ticks',
  k2Incl100ticks: 'k2Incl100ticks',
  k2Incl150ticks: 'k2Incl150ticks',
  k2Incl200ticks: 'k2Incl200ticks'
};

exports.Prisma.BinanceKagiFastScalarFieldEnum = {
  corretora: 'corretora',
  symbol: 'symbol',
  interval: 'interval',
  openTime: 'openTime',
  open: 'open',
  high: 'high',
  low: 'low',
  close: 'close',
  volume: 'volume',
  closeTime: 'closeTime',
  quoteAssetVolume: 'quoteAssetVolume',
  numberOfTrades: 'numberOfTrades',
  takerBuyBaseAssetVolume: 'takerBuyBaseAssetVolume',
  takerBuyQuoteAssetVolume: 'takerBuyQuoteAssetVolume',
  k2Incl5ticks: 'k2Incl5ticks',
  k2Incl15ticks: 'k2Incl15ticks',
  k2Incl25ticks: 'k2Incl25ticks',
  k2Incl50ticks: 'k2Incl50ticks',
  k2Incl100ticks: 'k2Incl100ticks',
  k2Incl150ticks: 'k2Incl150ticks',
  k2Incl200ticks: 'k2Incl200ticks'
};

exports.Prisma.BinanceRenko2xFastScalarFieldEnum = {
  corretora: 'corretora',
  symbol: 'symbol',
  interval: 'interval',
  openTime: 'openTime',
  open: 'open',
  high: 'high',
  low: 'low',
  close: 'close',
  volume: 'volume',
  closeTime: 'closeTime',
  quoteAssetVolume: 'quoteAssetVolume',
  numberOfTrades: 'numberOfTrades',
  takerBuyBaseAssetVolume: 'takerBuyBaseAssetVolume',
  takerBuyQuoteAssetVolume: 'takerBuyQuoteAssetVolume',
  k2Incl5ticks: 'k2Incl5ticks',
  k2Incl15ticks: 'k2Incl15ticks',
  k2Incl25ticks: 'k2Incl25ticks',
  k2Incl50ticks: 'k2Incl50ticks',
  k2Incl100ticks: 'k2Incl100ticks',
  k2Incl150ticks: 'k2Incl150ticks',
  k2Incl200ticks: 'k2Incl200ticks'
};

exports.Prisma.BinanceTradeCountFastScalarFieldEnum = {
  corretora: 'corretora',
  symbol: 'symbol',
  interval: 'interval',
  openTime: 'openTime',
  open: 'open',
  high: 'high',
  low: 'low',
  close: 'close',
  volume: 'volume',
  closeTime: 'closeTime',
  quoteAssetVolume: 'quoteAssetVolume',
  numberOfTrades: 'numberOfTrades',
  takerBuyBaseAssetVolume: 'takerBuyBaseAssetVolume',
  takerBuyQuoteAssetVolume: 'takerBuyQuoteAssetVolume',
  k2Incl500trades: 'k2Incl500trades',
  k2Incl1000trades: 'k2Incl1000trades',
  k2Incl2500trades: 'k2Incl2500trades',
  k2Incl5000trades: 'k2Incl5000trades',
  k2Incl7500trades: 'k2Incl7500trades',
  k2Incl10000trades: 'k2Incl10000trades'
};

exports.Prisma.BinanceKlineMonthScalarFieldEnum = {
  corretora: 'corretora',
  symbol: 'symbol',
  interval: 'interval',
  openTime: 'openTime',
  open: 'open',
  high: 'high',
  low: 'low',
  close: 'close',
  volume: 'volume',
  closeTime: 'closeTime',
  quoteAssetVolume: 'quoteAssetVolume',
  numberOfTrades: 'numberOfTrades',
  takerBuyBaseAssetVolume: 'takerBuyBaseAssetVolume',
  takerBuyQuoteAssetVolume: 'takerBuyQuoteAssetVolume'
};

exports.Prisma.BinanceKlineCacheScalarFieldEnum = {
  symbol: 'symbol',
  interval: 'interval',
  chartKind: 'chartKind',
  openTime: 'openTime',
  open: 'open',
  high: 'high',
  low: 'low',
  close: 'close',
  volume: 'volume',
  closeTime: 'closeTime',
  quoteAssetVolume: 'quoteAssetVolume',
  numberOfTrades: 'numberOfTrades',
  takerBuyBaseAssetVolume: 'takerBuyBaseAssetVolume',
  takerBuyQuoteAssetVolume: 'takerBuyQuoteAssetVolume'
};

exports.Prisma.BinanceKlineCache2ScalarFieldEnum = {
  symbol: 'symbol',
  chartKind: 'chartKind',
  interval: 'interval',
  openTime: 'openTime',
  open: 'open',
  high: 'high',
  low: 'low',
  close: 'close',
  volume: 'volume',
  closeTime: 'closeTime',
  quoteAssetVolume: 'quoteAssetVolume',
  numberOfTrades: 'numberOfTrades',
  takerBuyBaseAssetVolume: 'takerBuyBaseAssetVolume',
  takerBuyQuoteAssetVolume: 'takerBuyQuoteAssetVolume'
};

exports.Prisma.BinanceKlineGapScalarFieldEnum = {
  symbol: 'symbol',
  interval: 'interval',
  gapFrom: 'gapFrom',
  gapTo: 'gapTo'
};

exports.Prisma.AppConfigScalarFieldEnum = {
  key: 'key',
  value: 'value',
  description: 'description',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.LogErroScalarFieldEnum = {
  id: 'id',
  dataHora: 'dataHora',
  origem: 'origem',
  msgErro: 'msgErro'
};

exports.Prisma.KlineSymbolScalarFieldEnum = {
  symbol: 'symbol',
  ativo: 'ativo',
  requiredDays1m: 'requiredDays1m',
  requiredDays5m: 'requiredDays5m',
  requiredDays1h: 'requiredDays1h'
};

exports.Prisma.AffiliateApplicationScalarFieldEnum = {
  id: 'id',
  idAfiliado: 'idAfiliado',
  cnpjDigits: 'cnpjDigits',
  taxId: 'taxId',
  razaoSocial: 'razaoSocial',
  responsavel: 'responsavel',
  email: 'email',
  siteUrl: 'siteUrl',
  acceptedDocs: 'acceptedDocs',
  approved: 'approved',
  locale: 'locale',
  commissionAnnualUsdCents: 'commissionAnnualUsdCents',
  commissionMonthlyUsdCents: 'commissionMonthlyUsdCents',
  createdAt: 'createdAt'
};

exports.Prisma.AffiliatePayoutProfileScalarFieldEnum = {
  id: 'id',
  affiliateApplicationId: 'affiliateApplicationId',
  activeTab: 'activeTab',
  brRazaoSocial: 'brRazaoSocial',
  brCnpjDigits: 'brCnpjDigits',
  brBanco: 'brBanco',
  brTipoConta: 'brTipoConta',
  brAgencia: 'brAgencia',
  brNumeroConta: 'brNumeroConta',
  brChavePix: 'brChavePix',
  intPaymentMethod: 'intPaymentMethod',
  intPaypalEmail: 'intPaypalEmail',
  intBankName: 'intBankName',
  intAccountOrIban: 'intAccountOrIban',
  intSwiftBic: 'intSwiftBic',
  intAccountHolderName: 'intAccountHolderName',
  intCountry: 'intCountry',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
};

exports.Prisma.NullableJsonNullValueInput = {
  DbNull: Prisma.DbNull,
  JsonNull: Prisma.JsonNull
};

exports.Prisma.JsonNullValueInput = {
  JsonNull: Prisma.JsonNull
};

exports.Prisma.QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
};

exports.Prisma.NullsOrder = {
  first: 'first',
  last: 'last'
};

exports.Prisma.JsonNullValueFilter = {
  DbNull: Prisma.DbNull,
  JsonNull: Prisma.JsonNull,
  AnyNull: Prisma.AnyNull
};
exports.Role = exports.$Enums.Role = {
  user: 'user',
  admin: 'admin'
};

exports.Tier = exports.$Enums.Tier = {
  free: 'free',
  plus: 'plus',
  lite: 'lite'
};

exports.UserLevel = exports.$Enums.UserLevel = {
  RECRUTA: 'RECRUTA',
  APRENDIZ: 'APRENDIZ',
  EXPLORADOR: 'EXPLORADOR',
  JOGADOR: 'JOGADOR',
  AVANCADO: 'AVANCADO',
  ESPECIALISTA: 'ESPECIALISTA',
  MESTRE: 'MESTRE',
  ELITE: 'ELITE',
  LENDARIO: 'LENDARIO',
  SUPREMO: 'SUPREMO',
  MITICO: 'MITICO',
  CELESTIAL: 'CELESTIAL',
  DIVINO: 'DIVINO'
};

exports.AppLanguage = exports.$Enums.AppLanguage = {
  en: 'en',
  pt: 'pt'
};

exports.SenderType = exports.$Enums.SenderType = {
  system: 'system',
  user: 'user'
};

exports.TxType = exports.$Enums.TxType = {
  CREDIT: 'CREDIT',
  DEBIT: 'DEBIT',
  ADJUSTMENT: 'ADJUSTMENT'
};

exports.TxSource = exports.$Enums.TxSource = {
  STRIPE: 'STRIPE',
  PAGARME: 'PAGARME',
  SPEND: 'SPEND',
  REFUND: 'REFUND',
  ADMIN: 'ADMIN',
  EXPIRATION: 'EXPIRATION',
  BONUS: 'BONUS',
  PRIZE: 'PRIZE'
};

exports.CheckoutStatus = exports.$Enums.CheckoutStatus = {
  CREATED: 'CREATED',
  COMPLETED: 'COMPLETED',
  REFUNDED: 'REFUNDED',
  CANCELED: 'CANCELED',
  PARTIALLY_REFUNDED: 'PARTIALLY_REFUNDED',
  OVER_LIMIT: 'OVER_LIMIT'
};

exports.Prisma.ModelName = {
  User: 'User',
  UserBinanceConnection: 'UserBinanceConnection',
  UserBinanceSpotOrder: 'UserBinanceSpotOrder',
  AffiliateAccount: 'AffiliateAccount',
  AffiliateCoupon: 'AffiliateCoupon',
  ChartLayout: 'ChartLayout',
  ChartModel: 'ChartModel',
  UserNotification: 'UserNotification',
  AccessRequest: 'AccessRequest',
  EmailVerificationToken: 'EmailVerificationToken',
  PasswordResetToken: 'PasswordResetToken',
  UserCoinWallet: 'UserCoinWallet',
  CoinLedgerEntry: 'CoinLedgerEntry',
  WalletCredit: 'WalletCredit',
  StripeEvent: 'StripeEvent',
  StripeCheckoutSession: 'StripeCheckoutSession',
  StripePlanPayment: 'StripePlanPayment',
  AffiliatePlanPaymentMonthAgg: 'AffiliatePlanPaymentMonthAgg',
  AffiliateMonthAggInvoice: 'AffiliateMonthAggInvoice',
  PagarMeOrder: 'PagarMeOrder',
  BinanceKline: 'BinanceKline',
  BinanceKlineFast: 'BinanceKlineFast',
  BinanceRenkoFast: 'BinanceRenkoFast',
  BinanceRangeFast: 'BinanceRangeFast',
  BinanceKagiFast: 'BinanceKagiFast',
  BinanceRenko2xFast: 'BinanceRenko2xFast',
  BinanceTradeCountFast: 'BinanceTradeCountFast',
  BinanceKlineMonth: 'BinanceKlineMonth',
  BinanceKlineCache: 'BinanceKlineCache',
  BinanceKlineCache2: 'BinanceKlineCache2',
  BinanceKlineGap: 'BinanceKlineGap',
  AppConfig: 'AppConfig',
  LogErro: 'LogErro',
  KlineSymbol: 'KlineSymbol',
  AffiliateApplication: 'AffiliateApplication',
  AffiliatePayoutProfile: 'AffiliatePayoutProfile'
};

/**
 * This is a stub Prisma Client that will error at runtime if called.
 */
class PrismaClient {
  constructor() {
    return new Proxy(this, {
      get(target, prop) {
        let message
        const runtime = getRuntime()
        if (runtime.isEdge) {
          message = `PrismaClient is not configured to run in ${runtime.prettyName}. In order to run Prisma Client on edge runtime, either:
- Use Prisma Accelerate: https://pris.ly/d/accelerate
- Use Driver Adapters: https://pris.ly/d/driver-adapters
`;
        } else {
          message = 'PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `' + runtime.prettyName + '`).'
        }

        message += `
If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report`

        throw new Error(message)
      }
    })
  }
}

exports.PrismaClient = PrismaClient

Object.assign(exports, Prisma)
