
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */
// biome-ignore-all lint: generated file

Object.defineProperty(exports, "__esModule", { value: true });

const {
  Decimal,
  objectEnumValues,
  makeStrictEnum,
  Public,
  getRuntime,
  skip
} = require('./runtime/index-browser.js')


const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 6.19.2
 * Query Engine version: c2990dca591cba766e3b7ef5d9e8a84796e47ab7
 */
Prisma.prismaVersion = {
  client: "6.19.2",
  engine: "c2990dca591cba766e3b7ef5d9e8a84796e47ab7"
}

Prisma.PrismaClientKnownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientKnownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)};
Prisma.PrismaClientUnknownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientUnknownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientRustPanicError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientRustPanicError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientInitializationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientInitializationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientValidationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientValidationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`sqltag is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.empty = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`empty is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.join = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`join is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.raw = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`raw is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.validator = Public.validator

/**
* Extensions
*/
Prisma.getExtensionContext = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.getExtensionContext is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.defineExtension = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.defineExtension is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = objectEnumValues.instances.DbNull
Prisma.JsonNull = objectEnumValues.instances.JsonNull
Prisma.AnyNull = objectEnumValues.instances.AnyNull

Prisma.NullTypes = {
  DbNull: objectEnumValues.classes.DbNull,
  JsonNull: objectEnumValues.classes.JsonNull,
  AnyNull: objectEnumValues.classes.AnyNull
}



/**
 * Enums
 */

exports.Prisma.TransactionIsolationLevel = makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
});

exports.Prisma.UserScalarFieldEnum = {
  id: 'id',
  emailEnc: 'emailEnc',
  emailIv: 'emailIv',
  emailTag: 'emailTag',
  emailSearchHash: 'emailSearchHash',
  emailVerifiedAt: 'emailVerifiedAt',
  name: 'name',
  passwordHash: 'passwordHash',
  specialCodeHash: 'specialCodeHash',
  specialExpiresAt: 'specialExpiresAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  role: 'role',
  tier: 'tier',
  nickname: 'nickname',
  nicknameChanges: 'nicknameChanges',
  avatarId: 'avatarId',
  avatarBorder: 'avatarBorder',
  avatarSkinTone: 'avatarSkinTone',
  avatarColorTone: 'avatarColorTone',
  sevenPoints: 'sevenPoints',
  ganhoSimulado: 'ganhoSimulado',
  userLevel: 'userLevel',
  position: 'position',
  tmp: 'tmp',
  isDeleted: 'isDeleted',
  dataExclusao: 'dataExclusao',
  dataExpiracao: 'dataExpiracao',
  pushToken: 'pushToken',
  pushTokenUpdated: 'pushTokenUpdated',
  notifyMegaSena: 'notifyMegaSena',
  notifyLotofacil: 'notifyLotofacil',
  notifyQuina: 'notifyQuina',
  hideStatusBar: 'hideStatusBar',
  progress: 'progress',
  language: 'language',
  timezoneOffset: 'timezoneOffset'
};

exports.Prisma.ChartLayoutScalarFieldEnum = {
  userId: 'userId',
  slot: 'slot',
  config: 'config',
  updatedAt: 'updatedAt'
};

exports.Prisma.BioSavedConfigScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  name: 'name',
  private: 'private',
  config: 'config',
  mapDisplayByYear: 'mapDisplayByYear',
  likes: 'likes',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.UserNotificationScalarFieldEnum = {
  idNotification: 'idNotification',
  senderType: 'senderType',
  sender: 'sender',
  userId: 'userId',
  notification: 'notification',
  keySystem: 'keySystem',
  ativo: 'ativo',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  expiredDate: 'expiredDate'
};

exports.Prisma.AccessRequestScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  message: 'message',
  status: 'status',
  createdAt: 'createdAt'
};

exports.Prisma.EmailVerificationTokenScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  tokenHash: 'tokenHash',
  expiresAt: 'expiresAt',
  createdAt: 'createdAt'
};

exports.Prisma.PasswordResetTokenScalarFieldEnum = {
  tokenHash: 'tokenHash',
  userId: 'userId',
  expiresAt: 'expiresAt',
  createdAt: 'createdAt'
};

exports.Prisma.UserCoinWalletScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  balance: 'balance',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.CoinLedgerEntryScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  walletId: 'walletId',
  type: 'type',
  source: 'source',
  amount: 'amount',
  refId: 'refId',
  meta: 'meta',
  createdAt: 'createdAt'
};

exports.Prisma.WalletCreditScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  entryId: 'entryId',
  amount: 'amount',
  consumed: 'consumed',
  expiresAt: 'expiresAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.StripeEventScalarFieldEnum = {
  id: 'id',
  type: 'type',
  payload: 'payload',
  receivedAt: 'receivedAt',
  processedAt: 'processedAt'
};

exports.Prisma.StripeCheckoutSessionScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  status: 'status',
  amountTotalCents: 'amountTotalCents',
  currency: 'currency',
  coinsToCredit: 'coinsToCredit',
  pricingLabel: 'pricingLabel',
  completedAt: 'completedAt',
  createdAt: 'createdAt'
};

exports.Prisma.SubscriptionCancellationScalarFieldEnum = {
  id: 'id',
  subscriptionId: 'subscriptionId',
  userId: 'userId',
  cancelledAt: 'cancelledAt'
};

exports.Prisma.PagarMeOrderScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  status: 'status',
  amountTotalCents: 'amountTotalCents',
  currency: 'currency',
  coinsToCredit: 'coinsToCredit',
  pricingLabel: 'pricingLabel',
  qrCode: 'qrCode',
  qrCodeUrl: 'qrCodeUrl',
  pixCopyPaste: 'pixCopyPaste',
  expiresAt: 'expiresAt',
  completedAt: 'completedAt',
  createdAt: 'createdAt'
};

exports.Prisma.BioSimulationQueueScalarFieldEnum = {
  id: 'id',
  queueName: 'queueName',
  userId: 'userId',
  status: 'status',
  payload: 'payload',
  result: 'result',
  createdAt: 'createdAt'
};

exports.Prisma.BioSimulationStateScalarFieldEnum = {
  userId: 'userId',
  state: 'state',
  mapDisplayByYear: 'mapDisplayByYear',
  updatedAt: 'updatedAt'
};

exports.Prisma.BioAppConfigScalarFieldEnum = {
  key: 'key',
  value: 'value',
  description: 'description',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.BinanceKlineScalarFieldEnum = {
  symbol: 'symbol',
  interval: 'interval',
  openTime: 'openTime',
  open: 'open',
  high: 'high',
  low: 'low',
  close: 'close',
  volume: 'volume',
  closeTime: 'closeTime',
  quoteAssetVolume: 'quoteAssetVolume',
  numberOfTrades: 'numberOfTrades',
  takerBuyBaseAssetVolume: 'takerBuyBaseAssetVolume',
  takerBuyQuoteAssetVolume: 'takerBuyQuoteAssetVolume'
};

exports.Prisma.BinanceKlineFastScalarFieldEnum = {
  symbol: 'symbol',
  interval: 'interval',
  openTime: 'openTime',
  open: 'open',
  high: 'high',
  low: 'low',
  close: 'close',
  volume: 'volume',
  closeTime: 'closeTime',
  quoteAssetVolume: 'quoteAssetVolume',
  numberOfTrades: 'numberOfTrades',
  takerBuyBaseAssetVolume: 'takerBuyBaseAssetVolume',
  takerBuyQuoteAssetVolume: 'takerBuyQuoteAssetVolume'
};

exports.Prisma.BinanceKlineCacheScalarFieldEnum = {
  symbol: 'symbol',
  interval: 'interval',
  openTime: 'openTime',
  open: 'open',
  high: 'high',
  low: 'low',
  close: 'close',
  volume: 'volume',
  closeTime: 'closeTime',
  quoteAssetVolume: 'quoteAssetVolume',
  numberOfTrades: 'numberOfTrades',
  takerBuyBaseAssetVolume: 'takerBuyBaseAssetVolume',
  takerBuyQuoteAssetVolume: 'takerBuyQuoteAssetVolume'
};

exports.Prisma.BinanceKlineGapScalarFieldEnum = {
  symbol: 'symbol',
  interval: 'interval',
  gapFrom: 'gapFrom',
  gapTo: 'gapTo'
};

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
};

exports.Prisma.JsonNullValueInput = {
  JsonNull: Prisma.JsonNull
};

exports.Prisma.NullableJsonNullValueInput = {
  DbNull: Prisma.DbNull,
  JsonNull: Prisma.JsonNull
};

exports.Prisma.QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
};

exports.Prisma.NullsOrder = {
  first: 'first',
  last: 'last'
};

exports.Prisma.JsonNullValueFilter = {
  DbNull: Prisma.DbNull,
  JsonNull: Prisma.JsonNull,
  AnyNull: Prisma.AnyNull
};
exports.Role = exports.$Enums.Role = {
  user: 'user',
  admin: 'admin'
};

exports.Tier = exports.$Enums.Tier = {
  free: 'free',
  plus: 'plus',
  lite: 'lite'
};

exports.UserLevel = exports.$Enums.UserLevel = {
  RECRUTA: 'RECRUTA',
  APRENDIZ: 'APRENDIZ',
  EXPLORADOR: 'EXPLORADOR',
  JOGADOR: 'JOGADOR',
  AVANCADO: 'AVANCADO',
  ESPECIALISTA: 'ESPECIALISTA',
  MESTRE: 'MESTRE',
  ELITE: 'ELITE',
  LENDARIO: 'LENDARIO',
  SUPREMO: 'SUPREMO',
  MITICO: 'MITICO',
  CELESTIAL: 'CELESTIAL',
  DIVINO: 'DIVINO'
};

exports.BioLanguage = exports.$Enums.BioLanguage = {
  en: 'en',
  pt: 'pt'
};

exports.SenderType = exports.$Enums.SenderType = {
  system: 'system',
  user: 'user'
};

exports.TxType = exports.$Enums.TxType = {
  CREDIT: 'CREDIT',
  DEBIT: 'DEBIT',
  ADJUSTMENT: 'ADJUSTMENT'
};

exports.TxSource = exports.$Enums.TxSource = {
  STRIPE: 'STRIPE',
  PAGARME: 'PAGARME',
  SPEND: 'SPEND',
  REFUND: 'REFUND',
  ADMIN: 'ADMIN',
  EXPIRATION: 'EXPIRATION',
  BONUS: 'BONUS',
  PRIZE: 'PRIZE'
};

exports.CheckoutStatus = exports.$Enums.CheckoutStatus = {
  CREATED: 'CREATED',
  COMPLETED: 'COMPLETED',
  REFUNDED: 'REFUNDED',
  CANCELED: 'CANCELED',
  PARTIALLY_REFUNDED: 'PARTIALLY_REFUNDED',
  OVER_LIMIT: 'OVER_LIMIT'
};

exports.BioQueueStatus = exports.$Enums.BioQueueStatus = {
  PENDING: 'PENDING',
  RUNNING: 'RUNNING',
  COMPLETED: 'COMPLETED'
};

exports.Prisma.ModelName = {
  User: 'User',
  ChartLayout: 'ChartLayout',
  BioSavedConfig: 'BioSavedConfig',
  UserNotification: 'UserNotification',
  AccessRequest: 'AccessRequest',
  EmailVerificationToken: 'EmailVerificationToken',
  PasswordResetToken: 'PasswordResetToken',
  UserCoinWallet: 'UserCoinWallet',
  CoinLedgerEntry: 'CoinLedgerEntry',
  WalletCredit: 'WalletCredit',
  StripeEvent: 'StripeEvent',
  StripeCheckoutSession: 'StripeCheckoutSession',
  SubscriptionCancellation: 'SubscriptionCancellation',
  PagarMeOrder: 'PagarMeOrder',
  BioSimulationQueue: 'BioSimulationQueue',
  BioSimulationState: 'BioSimulationState',
  BioAppConfig: 'BioAppConfig',
  BinanceKline: 'BinanceKline',
  BinanceKlineFast: 'BinanceKlineFast',
  BinanceKlineCache: 'BinanceKlineCache',
  BinanceKlineGap: 'BinanceKlineGap'
};

/**
 * This is a stub Prisma Client that will error at runtime if called.
 */
class PrismaClient {
  constructor() {
    return new Proxy(this, {
      get(target, prop) {
        let message
        const runtime = getRuntime()
        if (runtime.isEdge) {
          message = `PrismaClient is not configured to run in ${runtime.prettyName}. In order to run Prisma Client on edge runtime, either:
- Use Prisma Accelerate: https://pris.ly/d/accelerate
- Use Driver Adapters: https://pris.ly/d/driver-adapters
`;
        } else {
          message = 'PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `' + runtime.prettyName + '`).'
        }

        message += `
If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report`

        throw new Error(message)
      }
    })
  }
}

exports.PrismaClient = PrismaClient

Object.assign(exports, Prisma)
